baseurl: http://brentrobbins.github.io/boostedwebgeek.com/
title: boostedwebgeek.com
description: All Things Visual
permalink: /:categories/:title/
google_analytics_code: UA-XXXXXXXX-7
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "default"
      published: true
prose:
  rooturl: "_posts"
  media: "assets/uploads"
  siteurl: "http://www.boostedwebgeek.com"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
